version: '3.8'

services:
  postgres-hotel-db:
    image: postgres:15
    container_name: postgres-hotel
    restart: always
    environment:
      POSTGRES_DB: postgres_hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "20025:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data  # Use a relative path or named volume

  app:
    container_name: web-content-api
    build: .
    depends_on:
      postgres-hotel-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-hotel-db:5432/postgres_hotel_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "2025:2025"

volumes:
  postgres_data:
    driver: local
