version: '3'
services:
  api-gateway:
    container_name: api-gateway
    build: .
    ports:
      - "30033:30033"
    restart: always
    volumes:
      - /opt/projects/teach/upload/images:/opt/projects/teach/upload/images